### ISSUE TITLE
Error Metrics

### ISSUE THREAD

**Issue by ameeguy** [shih8674/PSO-train-BP-NN#1]
Hello,

First of all I would like to thank you for providing the source code for the PSO NN algorithm. The code is excellently written and well commented. I was able to do some adjustments to fit my problem. However, I find changing the error metrics a bit tricky. I noticed you used mape, however, I want to be able to see the mse and squared also. Any help adjusting the code would be appreciated.

**Comment by shih8674** [comment]
Hi ameeguy, 

Thanks for your good advice. I have updated the new project 'PSO-train-BP-NN v2', changing the code structure and add the parameter setting for loss function and activation function. In parameter setting, it has some commonly used function, or you can easily build the functions you want in the setting. However this project has not established a function to draw the result graph, I will add the function in a few days, thanks!
